### ISSUE TITLE
Add waypoint ID number to GUI

### ISSUE THREAD

**Issue by mdbguy** [TinyCrocodile/Coursedrawer#14]
Selected waypoint info includes co-ordinates and angle.  Would be nice to see the waypoint ID number to cross reference with in game courseplay hud to help identify course trouble area.

**Comment by TinyCrocodile** [comment]
@mdbguy  Thank you for your idea i will do it and publish it wihin the next beta release. I'm sorry for replying so late. I totally missed your post as i am new to how github works. Hope this will not happen again.

**Comment by TinyCrocodile** [comment]
I will also implement a "GoTo Waypoint" - Function so one can navigate directly to a waypoint wich may have problems.

**Comment by TinyCrocodile** [comment]
Fixed in 5,3 beta release
