### ISSUE TITLE
Announcement of Version 5.3

### ISSUE THREAD

**Issue by TinyCrocodile** [TinyCrocodile/Coursedrawer#26]
I just released version 5.3 with a few improvements. 
I hope i fixed a few issus with this.
Feel free to try and report back.

**Comment by mdbguy** [comment]
Navigation by waypoint ID is working well.  Did encounter this issue as well #27

**Comment by TinyCrocodile** [comment]
I will fix it these days but first i need to get git working again i cant commit atm. 
Until then a workaraund is addinga new wp after the last or first then move the wp and remove the new created wp.
