### ISSUE TITLE
Error at loading

### ISSUE THREAD

**Issue by kferrano** [TinyCrocodile/Coursedrawer#29]
Get the error when opening the courseManager.xml:

> Information about invoking JIT debugging
> instead of this dialog box, see the bottom of this message.
>
> *************** Exception text **************
> System.Xml.XmlException: Unexpected token 'wait'. Expected is a space. Line 180, position 65.

>    bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
>    bei System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
>    bei System.Xml.XmlTextReaderImpl.ThrowExpectingWhitespace(Int32 pos)
>    bei System.Xml.XmlTextReaderImpl.ParseAttributes()
>    bei System.Xml.XmlTextReaderImpl.ParseElement()
>    bei System.Xml.XmlTextReaderImpl.ParseElementContent()
>    bei System.Xml.XmlTextReaderImpl.Read()
>    bei System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
>    bei System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
>    bei System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
>    bei System.Xml.XmlDocument.Load(XmlReader reader)
>    bei System.Xml.XmlDocument.Load(String filename)
>    bei CourseDrawer.clsCourse.ReadCourseXML() in C:\Users\TinyCrocodile\Source\Repos\Coursedrawer\CourseDrawer\classes\clsCourse.vb:Zeile 81.
>    bei CourseDrawer.clsCourseManager.CoursesReadXML(String file) in C:\Users\TinyCrocodile\Source\Repos\Coursedrawer\CourseDrawer\classes\clsCourseManager.vb:Zeile 64.
>    bei CourseDrawer.clsCourseManager..ctor(String sCourseManagerXml) in C:\Users\TinyCrocodile\Source\Repos\Coursedrawer\CourseDrawer\classes\clsCourseManager.vb:Zeile 10.
>    bei CourseDrawer.clsCourseManager.getInstance(String xmlFile, Boolean forceNew) in C:\Users\TinyCrocodile\Source\Repos\Coursedrawer\CourseDrawer\classes\clsCourseManager.vb:Zeile 26.
>    bei CourseDrawer.mainForm.butLoadCourse_Click(Object sender, EventArgs e) in C:\Users\TinyCrocodile\Source\Repos\Coursedrawer\CourseDrawer\forms\mainForm.vb:Zeile 322.
>    bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    bei System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>    bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    bei System.Windows.Forms.Control.WndProc(Message& m)
>    bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Geladene Assemblys **************
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2633.0 built by: NET471REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> CourseDrawer
>     Assembly-Version: 5.3.1.36676.
>     Win32-Version: 5.3.001.0.
>     CodeBase: file:///C:/Users/rzimp/Desktop/Neuer%20Ordner%20(5)/CourseDrawer.exe.
> ----------------------------------------
> Microsoft.VisualBasic
>     Assembly-Version: 10.0.0.0.
>     Win32-Version: 14.7.2556.0 built by: NET471REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll.
> ----------------------------------------
> System
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2556.0 built by: NET471REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
> ----------------------------------------
> System.Core
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2633.0 built by: NET471REL1LAST_C.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
> ----------------------------------------
> System.Windows.Forms
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2556.0 built by: NET471REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
> ----------------------------------------
> System.Drawing
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2556.0 built by: NET471REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
> ----------------------------------------
> System.Configuration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2556.0 built by: NET471REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
> ----------------------------------------
> System.Xml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> System.Runtime.Remoting
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2556.0 built by: NET471REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll.
> ----------------------------------------
> System.xml.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2556.0 built by: NET471REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Xml.resources.dll.
> ----------------------------------------
> System.Windows.Forms.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2556.0 built by: NET471REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
> ----------------------------------------
> mscorlib.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.2556.0 built by: NET471REL1.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable JIT (Just-In-Time) debugging, it must be in the
> Application or computer configuration file
> (machine.config) set the jitDebugging value in the system.windows.forms section.
> The application must be compiled with debugging enabled.
> 
> Zum Beispiel:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> If JIT debugging is enabled, all unhandled ones will be
> Exceptions sent to the JIT debugger on the
> Computer is registered, and not covered in this dialog box.
> 

```

**Comment by TinyCrocodile** [comment]
Thank you for submitting this issue. I will look into it as soon i can manage. What is happening after this message? Does it load the courses even if the error appears?

**Comment by kferrano** [comment]
He stays in charging mode, so he does not load the courses.

I downloaded Visual Studio and found out that the error is not due to CourseDrawer special courseplay
Here's a video I mean: https://youtu.be/BKY6vvgdr1A

**Comment by kferrano** [comment]
In addition, shows me for some reason the PDA map of the Mod Map which I use larger in comparison to the original (Map01) although the image dimensions are the same

**Comment by kferrano** [comment]
Or the courses are bigger than they should be
http://prntscr.com/j2kf1m

**Comment by kferrano** [comment]
I think the size does not work well
http://prntscr.com/j2kh5l
1.1 is actually at 1.2
and 2.1 is actually at 2.2
it looks like the courses will be doubled and moved twice as big

**Comment by TinyCrocodile** [comment]
What map do you use it thinks it is the same size as the stanard map. If it is 4x the standard size you need to rescale the pda map to resolution of 4096x4096. You can see it there where it says map size.

**Comment by kferrano** [comment]
I use the Nordfriesische Marsch Mod Map 4x https://www.fedaction-letsplay.de/aktuelle-projekte/ls17-meine-mod-map/

**Comment by TinyCrocodile** [comment]
This means you need tho rescale the PDA map image as i said in the previous post.

Thank you very much for this video. So you found the source of the error well done!
it would be interesting to know in wich casess the blankspace is missed.  Maybe i can improve the errorhandling and give users better information where to fix it from coursedrawer side.

**Comment by TinyCrocodile** [comment]
Closed for Cleanup
