### ISSUE TITLE
issue with recalculating angles

### ISSUE THREAD

**Issue by Opa-Andre** [TinyCrocodile/Coursedrawer#30]
Hi there,

I'm using a recorded coursefile which contains  a longer part driving straight from east to west. So the y value stays being the same value. The recorded file shows the angle value of "-90.00". When using your last release of course drawer on one of those waypoints, the value changes from -90.00 to 90.00. If I move one of the waypoints a little bit (just for checking) the new angle values will be calculated correctly (for example -89.00 or -91.00. Just when being straight it results in a positive 90.00 value which is wrong because this would be the opposite direction... could you fix this?

Thx much
Andre

**Comment by TinyCrocodile** [comment]
Hi Andre
Thank you for submitting this issue.
I will look into it!
I had some strange results as well but never that bad. 

TC

**Comment by TinyCrocodile** [comment]
Sorry for not doing this faster. I just had no time. Now i am away. Will look to fix it when i come home.

**Comment by Opa-Andre** [comment]
No problem - take your time. Real life comes first. :) Seems this is somehow an error / mistake also other course editor apps do.

**Comment by Opa-Andre** [comment]
Oops, did hit the wrong button. "close and comment". Therefore reopening.

**Comment by TinyCrocodile** [comment]
@Opa-Andre 
I found the problem and fixed it 
Please see Release 5.3.2-beta
Sorry for very long delay
