### ISSUE TITLE
moving waypoints with arrow keys?

### ISSUE THREAD

**Issue by andreasthu** [TinyCrocodile/Coursedrawer#33]
Hey guys.
I like coursedrawer to edit cp courses.
One tricky thing is the precise positioning of the waypoints.
I know, move with mouse on the map or type the coordinates in the right bottom fields.

My idea is, let us move the waypoints with the arriw keys on keyboard.
Key arrow left move the wp 0.25 0.5 or 1 m left, ...

Lg
Andreas

**Comment by TinyCrocodile** [comment]
Ok thank you for the sugestion let me see if i can do this. As for now i dont see a problem. It may take me a few days to get it done as i am not at home atm.

**Comment by TinyCrocodile** [comment]
I think a lot about usability of the coursedrawer i am absolutely not satisfied with its current state. I apreciate every input. My goal is to make it more the feeling of a cad program with better graphics and more direct feedback of movement and coursecreation. Its a long way to go...

**Comment by andreasthu** [comment]
thanks

**Comment by TinyCrocodile** [comment]
I will continue on a new Course Editor wich is mor up to date and will not do any more changes to this Repository. New Project will hopefully implement all the new stuff i coudn't achieve here.
Latest State of work is published in V6 and will not be maintained or supported.
