### ISSUE TITLE
missed isconnectingtrack="true" 

### ISSUE THREAD

**Issue by andreasthu** [TinyCrocodile/Coursedrawer#34]
Hey guys,
when i edit an field work course and save it, i missed the
isconnectingtrack="true"
entrys in the xml.
there is also no point to set them in the coursedrawer.

lg
andreas

**Comment by TinyCrocodile** [comment]
Thank you for this input.
Ok i did not know this is existing but i was aware of it must have someting like this. I will implement it as soon as i get home.
Lg martin

**Comment by andreasthu** [comment]
Hallo Martin 
Ok.
This variable is used when you generate a field work course with the new course generator funktion.
As example,  startpoint is aktual position, direction set to automatic, and then you must set a pair rounds of the field.
Lg
Andreas

**Comment by pvaiko** [comment]
A connecting track is a section of the fieldwork course where the vehicle is moving on the field with implements turned off, for example to move to the start of the up/down rows from the end of the headland, or to the next block (on fields with islands or non-convex shape).

**Comment by TinyCrocodile** [comment]
Done
