### ISSUE TITLE
Update Waypoints and XML files for FS 19 CP6

### ISSUE THREAD

**Issue by TinyCrocodile** [TinyCrocodile/Coursedrawer#37]
Implement new xml information in Coursedrawer to ensure no userdata is lost. 

- [x]  Make a list of all new xml attributes 
- [x]  Add Properties for new attributes 
- [x]  Update loading and saving procedures to read and write new attributes
Optional
- [x]  Provide changing control for attribute if necessery
- [x]  Implement a generic way to deal with unknown attributes to not loose data if someting changes in CP and Coursedrawer is not up to date

**Comment by PromGames** [comment]
Hello TinyCrocodile, Let me introduce myself and tell you a history about coursedrawer that you and many members of this community probably do not know, 

In 2011, coursedrawer was published in FSUK by Pawpouk in c#

Horoman in 2013 talked to him and ask permission to convert to VB, for the community and he did it and made it available to the community in VB. He added also the 4x capabilities.
I forked for that time the coursedrawer from horoman and start to learn VB and programming skills, and I used github coursedrawer repository open to all users. 

Six years ago. 2013 too, Claus (Satissis), developer and author of courseplay, was thinking to make another program and he create a [github ](Satissis/CourseplayEditor) where the system were capable to select and make automatically form savegames and mod files without any user intervention.

I presented coursedrawer as it was to CP developers, and they said (thomas), it was poor and not user friendly. I agreed.  Then I delete the github repositoty of coursedrawer and start the courseplay editor project on private repository in Gitlab

I decided to follow the direction stablished by satissis in 2013 and start developing a tool capable to automatically make all operations of images, selection etc useful and friendly.

Claus and our team at lsmodcompany has been using those versions for FS15 and FS17, and i will send FS19 version by this week on a private basis.

Well, the conclusion from this long talk is that you are developing the same tool than me. It is a copy? Yes, you have got from pseudex, erkasitori and they got from my github. It is aproblem, NO 

However, this can disturb ny intention to present courseplay editor to giants modhub

What if you help me to improve the courseplay editor, much more advanced programmed, and we can work together to get my ourseplay editor published in giants modhub. 

You can reach me on my email yalenk@gmail.com

Just an Image of  courseplay editor FS19 today

![image](https://user-images.githubusercontent.com/9979168/51939288-663e9e80-240f-11e9-9836-487581794aca.png)


![image](https://user-images.githubusercontent.com/9979168/51939227-3db6a480-240f-11e9-9d3c-694128e48ffd.png)

**Comment by TinyCrocodile** [comment]
Hello Prom Games 
I am glad to hear from you

Thank you very much for this detailed background Information about CourseDrawer.
I appreciate the grate amount of Work that Pawpouk, Horoman, You, Pseudex and all other developpers put into CourseDrawer.(see credits)

Let me explain how i did become the CourseDrawer developer.
A year ago i was playing a lot LS17 with courseplay and the wish to be able to edit Courses became bigger. I started to edit the coursefiles with notepad++ and the idea of having a tool for this task was born. I started searching for a already finished tool to do this Task. 

Then i found the CourseDrawer, the Coursplay Editor from Claus, and yCourse. At this time all of theese tools were outdated. I tested yCourse and was for some reason not really satisfied as it is based on the same Code as Coursedrawer. I used CourseDrawer for a while and began to see it was "it was poor and not user friendly". 

As no developer was around and i had a few pieces of VB and C# in school i planned to make some miner improvements for myself. But why not sharing improvements with others? So i asked Pseudex for permisson of taking over CD wich he did. As you did delete your repo this was the first repo i could find. So suddenly i was CourseDrawer developer as it was the best way to get the tool i wanted. As you can see in my Issues an Projects i am well awere of Coursedrawers lack of usability and all the problems. Multiple times i was thinking about starting from scratch but the fastest way for me with no programming background was to continue the work as i did until now. 

I know tihs is not my software but this is the power and idea behind open source software. I get some free piece of code and can contribute back for the benefit of all. If no dev is around somebody else can step in, fill the gap and take over. In my opinion the community owns that repo.

I am very happy you have a better version of a Corusplay Course-Editor and cant wait to test it. This looks very good and seems to be exactly what i wished all year long.
Can you provide a download link (even if is is old FS 17version ) please? As for some reason i cant find it. 

I dont think this version of CD is a problem for your version as it uses a different approach and is not very poular (maybe 4 users a day :-) and yours is better i am shure) 

Thank you for your offer. I have to think about it and let you know, when i decided how to continue. You should also know i am not a programmer and for some reason like job, family and other hobbies i did not accomplish a lot during this year.

Best regards 
Martin

**Comment by PromGames** [comment]
Good, I think we can get together a better tool at the end. 

I need you to create a user in gitlab and we will collaborate in private repository. I am using visual studio 2017. Then, wecan collaborate on the code.

Are you Swiss? From where? I have been working for more tha. 20 years in multinationals in Arau, rotkreutz and Cham. 

Prom

**Comment by TinyCrocodile** [comment]
Fixed and Closed
I will not continue here as i will move to other Project
